### ISSUE TITLE
Scoped values stop updating

### ISSUE THREAD

**Issue by mystrdat** [posva/vue-motion#10]
Hi and many thanks for the library!

I am having a strange issue where the scoped values stop updating once the animated transition has enough time to complete. However, if I keep updating the component data fast enough (in my case with `mousemove`) and the animation to the latest value doesn't complete, it happily runs forever. I've tried to record the behavior:

![2018-04-25_20-17-28](https://user-images.githubusercontent.com/1652895/39264707-d5de3d52-48c5-11e8-837d-ce0620cdefd1.gif)

The top value is from the component data passed to Motion, the bottom value is the same data scoped in Motion. Am I missing something obvious? Can add a code sample, though it's pretty much based on the example usage.

**Comment by posva** [comment]
I cannot see if something obvious is missing without any line of code 😆 
I'm interested in seeing a repro (as small as possible with the mouseover) as this could be a racing condition

**Comment by mystrdat** [comment]
While building the test case, I realized the problem is in how I'm updating the data. Next time I'll do that first. Everything works smoothly, sorry to bother!

**Comment by posva** [comment]
no worries, glad you solved the problem 🙂
