### ISSUE TITLE
How to use with dynamic growing/shrinking lists / default values.

### ISSUE THREAD

**Issue by rharink** [posva/vue-motion#14]
Hi, first of all, I love the library! but i'm struggling to create a dynamic carrousel that appends / removes items in a list. I get errors for the items that do not exist yet in the new list. Is there a way to provide default values for new items?

Simple example:
```
<template>
<ul>
  <Motion :values="children">
    <div slot-scope="_children">
      <div v-for="(child, index) in _children" :key="index">
        <p>{{child.offset}}</p>
      </div>
    </div>
  </Motion>
  <button v-on:click="testPush">test Push</button>
  <button v-on:click="test">test</button>
</ul>
</template>

<script lang="ts">
import { Motion } from "vue-motion"

export default {
  components: {
    Motion
  },
  data() {
    return {
      children: [{
        offset: 0,
      }],
    }
  },
  methods: {
    test() {
      this.$data.children = [{offset: 100}, {offset: 200}]
    },
    testPush() {
      this.$data.children.push({offset: 200})
    }
  }
}
</script>
```

Thanks!

**Comment by posva** [comment]
I released a version that fixed the problem of setting to a bigger array but I still need to manage adding elements and shrinking + growing arrays (right now, old values are not cleaned up)

**Comment by Rauwekost** [comment]
Ok, thanks for the effort!
