### ISSUE TITLE
Is there human understandable example how to use it?

### ISSUE THREAD

**Issue by iamrddlr** [posva/vue-motion#17]
Ok. This example from Docs make no sense for me. Sorry.

```
<Motion :value="offset" tag="div">
  <div slot-scope="props" :style="{ transform: `translateX(${props.value}px)` }"></div>
</Motion>
// in the component
this.offset = 200
```

1. What `component` you are talking about?
2. What is `this.offset`?
3. What is `props`?

**Comment by posva** [comment]
There are other examples with documentation at https://posva.net/vue-motion/#/home

But please, be more respectful towards wy work next time, thanks

**Comment by iamrddlr** [comment]
@posva I am respectful to your work, it's just it's painful to see that not many people can consume the results of your work, because of documentation.
