### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by manniL** [posva/vue-motion#18]
I can't properly access https://posva.net/vue-motion/ 🤔 

![image](https://user-images.githubusercontent.com/640208/50649188-24881880-0f75-11e9-8392-60834c516040.png)

**Comment by posva** [comment]
seems like a cache problem on one of the CDN :/
try clearing the cache
It works fine on my end

**Comment by manniL** [comment]
Looks like it's a Firefox issue :man_shrugging:
