### ISSUE TITLE
Demo Page is Broken

### ISSUE THREAD

**Issue by jefrydco** [posva/vue-motion#19]
Hi @posva , thanks for bringing react plugin into vue world. But it seems currently the demo was broken, when I open the link on the description above, it didn't show anything. I saw the console and this message was appear.
![image](https://user-images.githubusercontent.com/20434351/52385949-6b0ded00-2ab6-11e9-92d4-0da055810549.png)

**Comment by posva** [comment]
Hey, I'm glad you like it. I tested multiple times in different browser but everything looks fine. I think some CDN was broken at some point and that was the error
