### ISSUE TITLE
Docs and demo pages are down

### ISSUE THREAD

**Issue by sarneeh** [posva/vue-motion#8]
Like in the title. The websites are down :(

**Comment by posva** [comment]
It was probably a problem on Cloudflare or something else. They look to be back up 🙂

**Comment by sarneeh** [comment]
@posva Thanks for fast reaction ;)

**Comment by posva** [comment]
Just to be clear, I didn't do anything 😆, it was probably something temporal

**Comment by sarneeh** [comment]
I know, but you did let me know it's working again. That's something 😃
